# Macro file for example B2
# 
# To be run preferably in batch, without graphics:
# % exampleB2[a,b] run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
/gun/particle neutron
/gun/energy 100 keV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 300 keV 
/run/beamOn 10000

/gun/particle neutron
/gun/energy 500 keV 
/run/beamOn 10000

/gun/particle neutron
/gun/energy 700 keV 
/run/beamOn 10000

/gun/particle neutron
/gun/energy 900 keV 
/run/beamOn 10000

